apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubelab.fullname" . }}
  labels:
    {{- include "kubelab.labels" . | nindent 4 }}
data:
  GREETING: {{ .Values.greeting | quote }}
  message.txt: |
    Deployed by Helm release "{{ .Release.Name }}" into namespace "{{ .Release.Namespace }}".
