apiVersion: v1
kind: Namespace
metadata:
  name: capstone
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: capstone-quota
  namespace: capstone
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.memory: 4Gi
