apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: kubelab/app:v1
          imagePullPolicy: Never
          env:
            - name: GREETING
              value: "hello from the base"
